module.exports = [
  {
    norad: null,
    aliases: ['AO-91', 'RADFXSAT', 'FOX-1B'],
    uplinkMhz: 435.25,
    downlinkMhz: 145.96,
    mode: 'FM',
    callsign: null,
    status: 'Active',
    notes: '67 Hz CTCSS. Do not attempt access while in eclipse due to battery status.',
  },
  {
    norad: null,
    aliases: ['AO-123', 'ASRTU-1'],
    uplinkMhz: 145.85,
    downlinkMhz: 435.4,
    mode: 'FM',
    callsign: null,
    status: 'Active',
    notes: '67 Hz CTCSS.',
  },
  {
    norad: null,
    aliases: ['CAS-3H', 'LILACSAT-2'],
    uplinkMhz: 144.35,
    downlinkMhz: 437.2,
    mode: 'FM / Telemetry Beacon',
    callsign: null,
    status: 'Scheduled',
    notes:
      'FM transponder has no fixed schedule. Telemetry beacon on 437.200 MHz when transponder is off.',
  },
  {
    norad: null,
    aliases: ['IO-86', 'LAPAN-A2'],
    uplinkMhz: 145.88,
    downlinkMhz: 435.88,
    mode: 'FM',
    callsign: null,
    status: 'Scheduled',
    notes:
      '88.5 Hz CTCSS. Low inclination orbit (+/- 30 deg equator). Schedule: https://community.libre.space/t/lapan-a2-io-86-schedule-2026',
  },
  {
    norad: 25544,
    aliases: ['ISS'],
    uplinkMhz: 145.99,
    downlinkMhz: 437.8,
    mode: 'FM',
    callsign: 'ARISS',
    status: 'Active',
    notes: '67 Hz CTCSS. See ARISS status for latest operational updates.',
  },
  {
    norad: null,
    aliases: ['PO-101', 'DIWATA-2'],
    uplinkMhz: 437.5,
    downlinkMhz: 145.9,
    mode: 'FM',
    callsign: null,
    status: 'Uncertain',
    notes: '141.3 Hz CTCSS. Reported as failing; FM transponder often activated by schedule.',
  },
  {
    norad: null,
    aliases: ['QMR-KWT-2', 'RS95S'],
    uplinkMhz: 145.92,
    downlinkMhz: 436.95,
    mode: 'FM / SSTV',
    callsign: null,
    status: 'Testing',
    notes: '67 Hz CTCSS. During testing; may transmit SSTV images.',
  },
  {
    norad: null,
    aliases: ['SO-50', 'SAUDISAT-1C'],
    uplinkMhz: 145.85,
    downlinkMhz: 436.795,
    mode: 'FM',
    callsign: null,
    status: 'Active',
    notes: '67 Hz CTCSS. Has 10-minute timer. Arm with 2-second carrier and 74.4 Hz tone.',
  },
  {
    norad: null,
    aliases: ['SO-125', 'HADES-ICM'],
    uplinkMhz: 145.875,
    downlinkMhz: 436.666,
    mode: 'FM',
    callsign: null,
    status: 'Active',
    notes: null,
  },
];
